server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8765/eureka/

spring:
  application:
    name: mcsv-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cine-dev
          uri: http://localhost:8081
          predicates:
            - Path=/cine/**
        - id: usuarios-dev
          uri: http://localhost:8082
          predicates:
            - Path=/usuarios/**