server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8765/

spring:
  application:
    name: mcsv-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cine-dev
          uri: http://cine-service:8081
          predicates:
            - Path=/cine/**
        - id: costos-cine-dev
          uri: http://cine-service:8081
          predicates:
            - Path=/costoCine/**
        - id: salas-dev
          uri: http://cine-service:8081
          predicates:
            - Path=/salas/**
        - id: snacks-dev
          uri: http://cine-service:8081
          predicates:
            - Path=/snacks/**
