server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8765/

spring:
  application:
    name: mcsv-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cine-dev
          uri: http://cine-service:8081
          predicates:
            - Path=/cine/**
        - id: costos-cine-dev
          uri: http://cine-service:8081
          predicates:
            - Path=/costoCine/**
        - id: salas-dev
          uri: http://cine-service:8081
          predicates:
            - Path=/salas/**
        - id: snacks-dev
          uri: http://cine-service:8081
          predicates:
            - Path=/snacks/**
        - id: anuncios-dev
          uri: http://anuncios-service:8084
          predicates:
            - Path=/anuncio/**
        - id: materialAnuncio-dev
          uri: http://anuncios-service:8084
          predicates:
            - Path=/materialAnuncio/**
        - id: propiedadAnuncio-dev
          uri: http://anuncios-service:8084
          predicates:
            - Path=/propiedadAnuncio/**
        - id: bloqueoAnuncios-dev
          uri: http://cine-service:8081
          predicates:
            - Path=/bloqueoAnuncios/**
        - id: categorias-dev
          uri: http://movies-service:8082
          predicates:
            - Path=/api/v1/categorias/**
        - id: horarios-dev
          uri: http://movies-service:8082
          predicates:
            - Path=/api/v1/horarios/**
        - id: peliculas-dev
          uri: http://movies-service:8082
          predicates:
            - Path=/api/v1/peliculas/**     
        - id: peliculas-dev
          uri: http://movies-service:8082
          predicates:
            - Path=/api/v1/peliculas/**     
        - id: detalle-categoria-dev
          uri: http://movies-service:8082
          predicates:
            - Path=/api/v1/posters/**   
        - id: posters-dev
          uri: http://movies-service:8082
          predicates:
            - Path=/api/v1/posters/**  
        - id: auth-dev
          uri: http://usuarios-service:8083
          predicates:
            - Path=/v1/auth/**  
        - id: users-dev
          uri: http://usuarios-service:8083
          predicates:
            - Path=/v1/users/**  
        - id: calificaciones-peliculas-dev
          uri: http://calificaciones-service:8091
          predicates:
            - Path=/api/calificaciones/peliculas/**  
        - id: calificaciones-salas-dev
          uri: http://calificaciones-service:8091
          predicates:
            - Path=/api/calificaciones/salas/**  
        - id: calificaciones-snacks-dev
          uri: http://calificaciones-service:8091
          predicates:
            - Path=/api/calificaciones/snacks/**  
        - id: ventas-asientos-dev
          uri: http://ventas-service:8090
          predicates:
            - Path=/api/ventas/asientos/**  
        - id: ventas-boletos-dev
          uri: http://ventas-service:8090
          predicates:
            - Path=/api/ventas/boletos/**  
        - id: ventas-ventas-dev
          uri: http://ventas-service:8090
          predicates:
            - Path=/api/ventas/ventas/**            
        - id: ventas-snacks-dev
          uri: http://ventas-service:8090
          predicates:
            - Path=/api/ventas/venta-snacks/**         
