name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gateway:${GITHUB_SHA} .
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway:${GITHUB_SHA}

      # 4. Configurar credenciales AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5. Instalar kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      # 6. Autenticarse con EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name P2-SA --region ${{ secrets.AWS_REGION }}

      # 7. Desplegar a Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/gateway-deploy gateway=${{ secrets.DOCKER_USERNAME }}/gateway:${GITHUB_SHA}
          kubectl rollout status deployment/gateway-deploy
